-- Add migration script here
ALTER TABLE channels ALTER COLUMN id SET NOT NULL;
ALTER TABLE channels ALTER COLUMN name SET NOT NULL;

ALTER TABLE emoji ALTER COLUMN id SET NOT NULL;
ALTER TABLE emoji ALTER COLUMN asset_url SET NOT NULL;

ALTER TABLE guilds ALTER COLUMN id SET NOT NULL;
ALTER TABLE guilds ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE guilds ALTER COLUMN name SET NOT NULL;
ALTER TABLE guilds ALTER COLUMN users SET NOT NULL;

ALTER TABLE members ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE members ALTER COLUMN guild_id SET NOT NULL;

ALTER TABLE messages ALTER COLUMN id SET NOT NULL;
ALTER TABLE messages ALTER COLUMN channel SET NOT NULL;

ALTER TABLE users ALTER COLUMN id SET NOT NULL;
ALTER TABLE guilds ALTER COLUMN name SET NOT NULL;
